### ISSUE TITLE
SQLighterRs should use concrete types

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#14]
So far the interface `SQLighterRs` uses mostly Number as return type. This is not god because you have to cast the results all the time. 

Could you please change the following interface methods like this:

```
public double getDouble(int index);
public long getLong(int index);
public int getInt(int index);
```

**Comment by vals-productions** [comment]
Then you'd need to check for SQL NULL all the time... 'cause otherwise you can get NullPointerException...

I can change them to return objects, i.e. Double, Long, Integer. I can also add getNumber to return Number as it's very convenient for iOS as it j2objc'd to NSNumber directly.

Also, you do not need to cast, Number has intValue(), longValue(), etc. methods.

**Comment by vals-productions** [comment]
done
