### ISSUE TITLE
executeChange should be executeUpdate

### ISSUE THREAD

**Issue by confile** [vals-productions/sqlighter#16]
This might be a better notation: 

```
executeChange  ->  executeUpdate
executeSelect -> executeQuery
```

This a common convention for example in Grails.

**Comment by vals-productions** [comment]
executeUpdate would seem to be related to update queries only, like UPDATE <TABLE_NAME>  SET..., but executeChange is related queries that make any changes to the database - INSERT, UPDATE, ALTER, CREATE, etc. that's why.

executeSelect is only for SELECT ... FROM ...

that's why this naming is chosen.
